/**
 * Centralized Sidebar Theme Definitions
 * Curated for high contrast, stunning aesthetics, and 100% crystal-clear readability
 * in BOTH Dark Mode and Light Mode.
 */

export const SIDEBAR_THEMES = [
  {
    id: 'midnight',
    name: 'Midnight Slate',
    description: 'Deep modern slate navy with icy crystal accents (Default)',
    swatchBg: 'from-slate-900 via-slate-900 to-slate-950',
    primaryColor: '#6366f1',
    // Sidebar styles
    asideBg: 'bg-slate-900 border-r border-white/10 text-slate-100',
    headerBg: 'bg-slate-900/95 border-b border-white/10 text-white',
    titleText: 'text-white',
    subtitleText: 'text-primary-300 font-medium',
    navDefault: 'text-slate-300 hover:text-white hover:bg-white/10',
    navActive: 'bg-gradient-to-r from-primary-600 to-accent-600 text-white shadow-lg shadow-primary-500/25 border border-white/15 font-bold',
    groupDefault: 'text-slate-300 hover:text-white hover:bg-white/10',
    groupActive: 'bg-white/10 text-white border border-white/15',
    groupChevron: 'text-slate-300',
    groupBorder: 'border-white/15',
    divider: 'border-white/10',
    profileCard: 'bg-gradient-to-b from-white/[0.08] to-white/[0.03] border-white/15 shadow-xl shadow-black/20',
    profileTopAccent: 'from-transparent via-primary-400/40 to-transparent',
    profileName: 'text-white',
    profileSub: 'text-slate-300',
    roleBadge: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    powerButton: 'bg-gradient-to-br from-rose-500 via-red-600 to-rose-700 hover:from-rose-600 hover:to-red-800 text-white shadow-lg shadow-rose-600/30 border border-rose-400/30'
  },
  {
    id: 'scarletRed',
    name: 'Crimson Scarlet Red',
    description: 'Vibrant school crimson red with crisp white typography & gold accents',
    swatchBg: 'from-[#d32f2f] via-[#c62828] to-[#b71c1c]',
    primaryColor: '#d32f2f',
    // Sidebar styles
    asideBg: 'bg-[#b71c1c] border-r border-red-900/40 text-white',
    headerBg: 'bg-[#991b1b]/95 border-b border-white/15 text-white',
    titleText: 'text-white',
    subtitleText: 'text-amber-200 font-semibold',
    navDefault: 'text-red-100 hover:text-white hover:bg-white/15',
    navActive: 'bg-white text-red-700 shadow-lg shadow-black/25 border border-white font-extrabold',
    groupDefault: 'text-red-100 hover:text-white hover:bg-white/15',
    groupActive: 'bg-black/20 text-white border border-white/20 font-bold',
    groupChevron: 'text-red-200',
    groupBorder: 'border-white/20',
    divider: 'border-red-400/20',
    profileCard: 'bg-black/25 border-white/20 shadow-xl shadow-black/30',
    profileTopAccent: 'from-transparent via-amber-300/60 to-transparent',
    profileName: 'text-white',
    profileSub: 'text-red-100 font-mono font-bold',
    roleBadge: 'bg-amber-400/25 text-amber-200 border-amber-400/40 font-bold',
    powerButton: 'bg-white hover:bg-amber-50 text-red-700 hover:text-red-800 shadow-lg shadow-black/30 border border-white/80'
  },
  {
    id: 'cleanLight',
    name: 'Executive Pure White',
    description: 'Clean bright pearl finish with high-contrast dark text & bright blue active items',
    swatchBg: 'from-[#ffffff] via-[#f8fafc] to-[#e2e8f0]',
    primaryColor: '#2563eb',
    // Sidebar styles (explicitly dark text so it is 100% visible in BOTH light & dark modes!)
    asideBg: 'bg-white border-r border-slate-300 shadow-xl text-slate-900',
    headerBg: 'bg-slate-50 border-b border-slate-200 text-slate-900',
    titleText: 'text-slate-950 font-black',
    subtitleText: 'text-blue-600 font-bold',
    navDefault: 'text-slate-700 hover:text-slate-950 hover:bg-slate-100 font-semibold',
    navActive: 'bg-gradient-to-r from-blue-600 to-indigo-600 text-white shadow-md shadow-blue-500/30 border border-blue-700 font-extrabold',
    groupDefault: 'text-slate-700 hover:text-slate-950 hover:bg-slate-100 font-semibold',
    groupActive: 'bg-slate-100 text-slate-950 border border-slate-300 font-bold',
    groupChevron: 'text-slate-600',
    groupBorder: 'border-slate-300',
    divider: 'border-slate-200',
    profileCard: 'bg-slate-50 border-slate-300/90 shadow-md',
    profileTopAccent: 'from-transparent via-blue-500/50 to-transparent',
    profileName: 'text-slate-950 font-black',
    profileSub: 'text-slate-600 font-mono font-bold',
    roleBadge: 'bg-blue-100 text-blue-800 border-blue-300 font-bold',
    powerButton: 'bg-gradient-to-br from-rose-500 via-red-600 to-rose-700 hover:from-rose-600 hover:to-red-800 text-white shadow-md shadow-rose-600/30 border border-rose-400/30'
  },
  {
    id: 'ocean',
    name: 'Royal Ocean Navy',
    description: 'Deep royal maritime blue with electric cyan highlights',
    swatchBg: 'from-[#0b192e] via-[#0f2444] to-[#071324]',
    primaryColor: '#06b6d4',
    // Sidebar styles
    asideBg: 'bg-[#0b192e] border-r border-cyan-500/20 text-cyan-100',
    headerBg: 'bg-[#0b192e]/95 border-b border-cyan-500/20 text-white',
    titleText: 'text-white',
    subtitleText: 'text-cyan-300 font-medium',
    navDefault: 'text-cyan-100/80 hover:text-white hover:bg-cyan-500/15',
    navActive: 'bg-gradient-to-r from-blue-600 via-cyan-600 to-teal-500 text-white shadow-lg shadow-cyan-500/25 border border-cyan-400/30 font-bold',
    groupDefault: 'text-cyan-100/80 hover:text-white hover:bg-cyan-500/15',
    groupActive: 'bg-cyan-950/80 text-cyan-200 border border-cyan-500/30',
    groupChevron: 'text-cyan-300',
    groupBorder: 'border-cyan-500/20',
    divider: 'border-cyan-500/20',
    profileCard: 'bg-gradient-to-b from-cyan-950/50 to-slate-900/70 border-cyan-500/30 shadow-xl shadow-black/30',
    profileTopAccent: 'from-transparent via-cyan-400/50 to-transparent',
    profileName: 'text-white',
    profileSub: 'text-cyan-200 font-mono',
    roleBadge: 'bg-cyan-500/25 text-cyan-300 border-cyan-400/40',
    powerButton: 'bg-gradient-to-br from-rose-500 via-red-600 to-rose-700 hover:from-rose-600 hover:to-red-800 text-white shadow-lg shadow-rose-600/30 border border-rose-400/30'
  },
  {
    id: 'emerald',
    name: 'Imperial Emerald',
    description: 'Rich dark forest green with glowing mint accents',
    swatchBg: 'from-[#052219] via-[#083326] to-[#031913]',
    primaryColor: '#10b981',
    // Sidebar styles
    asideBg: 'bg-[#052219] border-r border-emerald-500/20 text-emerald-100',
    headerBg: 'bg-[#052219]/95 border-b border-emerald-500/20 text-white',
    titleText: 'text-white',
    subtitleText: 'text-emerald-300 font-medium',
    navDefault: 'text-emerald-100/80 hover:text-white hover:bg-emerald-500/15',
    navActive: 'bg-gradient-to-r from-emerald-600 via-teal-600 to-cyan-600 text-white shadow-lg shadow-emerald-500/25 border border-emerald-400/30 font-bold',
    groupDefault: 'text-emerald-100/80 hover:text-white hover:bg-emerald-500/15',
    groupActive: 'bg-emerald-950/80 text-emerald-200 border border-emerald-500/30',
    groupChevron: 'text-emerald-300',
    groupBorder: 'border-emerald-500/20',
    divider: 'border-emerald-500/20',
    profileCard: 'bg-gradient-to-b from-emerald-950/60 to-slate-950/70 border-emerald-500/30 shadow-xl shadow-black/30',
    profileTopAccent: 'from-transparent via-emerald-400/50 to-transparent',
    profileName: 'text-white',
    profileSub: 'text-emerald-200 font-mono',
    roleBadge: 'bg-emerald-500/25 text-emerald-300 border-emerald-400/40',
    powerButton: 'bg-gradient-to-br from-rose-500 via-red-600 to-rose-700 hover:from-rose-600 hover:to-red-800 text-white shadow-lg shadow-rose-600/30 border border-rose-400/30'
  },
  {
    id: 'purple',
    name: 'Royal Velvet Plum',
    description: 'Opulent deep violet with vibrant lilac & fuchsia illumination',
    swatchBg: 'from-[#1a0c2e] via-[#241040] to-[#120720]',
    primaryColor: '#a855f7',
    // Sidebar styles
    asideBg: 'bg-[#1a0c2e] border-r border-purple-500/20 text-purple-100',
    headerBg: 'bg-[#1a0c2e]/95 border-b border-purple-500/20 text-white',
    titleText: 'text-white',
    subtitleText: 'text-purple-300 font-medium',
    navDefault: 'text-purple-100/80 hover:text-white hover:bg-purple-500/15',
    navActive: 'bg-gradient-to-r from-purple-600 via-fuchsia-600 to-pink-500 text-white shadow-lg shadow-purple-500/25 border border-purple-400/30 font-bold',
    groupDefault: 'text-purple-100/80 hover:text-white hover:bg-purple-500/15',
    groupActive: 'bg-purple-950/80 text-purple-200 border border-purple-500/30',
    groupChevron: 'text-purple-300',
    groupBorder: 'border-purple-500/20',
    divider: 'border-purple-500/20',
    profileCard: 'bg-gradient-to-b from-purple-950/60 to-slate-950/70 border-purple-500/30 shadow-xl shadow-black/30',
    profileTopAccent: 'from-transparent via-purple-400/50 to-transparent',
    profileName: 'text-white',
    profileSub: 'text-purple-200 font-mono',
    roleBadge: 'bg-purple-500/25 text-purple-300 border-purple-400/40',
    powerButton: 'bg-gradient-to-br from-rose-500 via-red-600 to-rose-700 hover:from-rose-600 hover:to-red-800 text-white shadow-lg shadow-rose-600/30 border border-rose-400/30'
  },
  {
    id: 'carbon',
    name: 'Obsidian Jet Black',
    description: 'Pure stealth carbon dark with crisp high-contrast white text',
    swatchBg: 'from-[#09090b] via-[#111115] to-[#040405]',
    primaryColor: '#ffffff',
    // Sidebar styles
    asideBg: 'bg-[#09090b] border-r border-white/10 text-zinc-100',
    headerBg: 'bg-[#09090b]/95 border-b border-white/10 text-white',
    titleText: 'text-white',
    subtitleText: 'text-zinc-400 font-medium',
    navDefault: 'text-zinc-400 hover:text-white hover:bg-white/10',
    navActive: 'bg-gradient-to-r from-zinc-800 to-zinc-700 text-white shadow-lg shadow-black/50 border border-zinc-500/40 font-bold',
    groupDefault: 'text-zinc-400 hover:text-white hover:bg-white/10',
    groupActive: 'bg-zinc-900 text-zinc-100 border border-zinc-700/50',
    groupChevron: 'text-zinc-400',
    groupBorder: 'border-white/15',
    divider: 'border-white/10',
    profileCard: 'bg-gradient-to-b from-zinc-900 to-black border-zinc-800 shadow-xl',
    profileTopAccent: 'from-transparent via-zinc-400/30 to-transparent',
    profileName: 'text-white',
    profileSub: 'text-zinc-400 font-mono',
    roleBadge: 'bg-zinc-800 text-zinc-300 border-zinc-600',
    powerButton: 'bg-gradient-to-br from-rose-500 via-red-600 to-rose-700 hover:from-rose-600 hover:to-red-800 text-white shadow-lg shadow-rose-600/30 border border-rose-400/30'
  }
];

export const getSidebarTheme = (themeId) => {
  return SIDEBAR_THEMES.find(t => t.id === themeId) || SIDEBAR_THEMES[0];
};
